---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: containers-quickstarts-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/garethahealy/containers-quickstarts.git
    - name: revision
      value: tekton-agents
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-agent-ansible-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/containers-quickstarts/tekton-agent-ansible:latest
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-agent-ansible-build-pipeline
spec:
  resources:
    - name: containers-quickstarts-git
      type: git
    - name: tekton-agent-ansible-image
      type: image
  tasks:
    - name: build-tekton-agent-ansible
      taskRef:
        name: buildah
        kind: ClusterTask
      resources:
        inputs:
          - name: source
            resource: containers-quickstarts-git
        outputs:
          - name: image
            resource: tekton-agent-ansible-image
      params:
        - name: DOCKERFILE
          value: tekton-agents/tekton-agent-ansible/Dockerfile
        - name: TLSVERIFY
          value: "false"